project:
  type: website

website:
  title: "Dan's NAO notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/naobservatory/dans-public-notebook
format:
  html:
    theme: flatly 
    css: styles.css



